# Generated by Django 5.0.6 on 2024-07-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=300)),
                ('agensi_plan', models.CharField(choices=[('a', 'JKDM'), ('b', 'JANM'), ('a', 'JPPH'), ('b', 'LADA'), ('a', 'PERB')], max_length=1)),
                ('unique_code', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_plan',
            field=models.CharField(choices=[('a', 'Standard'), ('b', 'Premium'), ('a', 'Deluxe')], max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='unique_code',
            field=models.CharField(max_length=300),
        ),
    ]
